es:
  - host: 127.0.0.1
    port: 92001
    userName:
    password:
    maxRetries: 10
  - host: 127.0.0.1
    port: 9201
    userName:
    password:
    maxRetries: 10
  - host: 192.168.106.128
    port: 9201
    userName:
    password:
    maxRetries: 10
crypto:
  key: R2tY5uI9oP0sD3fG
  bcryptStrength: 16 #加密长度
